name: Bug report
description: Create a report to help us improve
body:
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      options:
        - Windows x64
        - Windows x86
        - Linux x64
        - Linux x86
        - Mac
        - Android
        - iOS
        - Xbox One
        - PlayStation 4
        - Nintendo Switch
        - PlayStation Vita
        - Nintendo 3DS
        - Other (please specify)
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: DevilutionX version
      options:
        - 1.4.1 (latest release)
        - 1.4.0
        - 1.3.0
        - 1.2.1
        - 1.1.0
        - Custom build (please specify commit ID)
        - Other (please specify version number)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: input
    id: expected-behavior
    attributes:
      label: Expected Behavior
      placeholder: A clear and concise description of what you expected to happen.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      placeholder: Any other context about the problem here (screenshots, videos, code blocks, etc.).
